export const teams = [
  {
    id: 'valorant',
    game: 'VALORANT',
    tag: 'OT',
    color: '#FF4655',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'IGL', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Entry', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Sniper', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Controller', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Flex', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'counterstrike',
    game: 'COUNTER-STRIKE',
    tag: 'OT',
    color: '#F0A500',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'IGL', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'AWPer', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Entry', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Support', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Lurker', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'r6-main',
    game: 'RAINBOW 6 — MAIN',
    tag: 'OT',
    color: '#009BDE',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'IGL', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Fragger', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Support', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Flex', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Roamer', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'r6-academy',
    game: 'RAINBOW 6 — ACADEMY',
    tag: 'OT',
    color: '#00A8E0',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'IGL', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Fragger', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Support', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Flex', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Roamer', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'iracing',
    game: 'iRACING',
    tag: 'OT',
    color: '#00C853',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'Driver', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Driver', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Driver', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'clashroyale',
    game: 'CLASH ROYALE',
    tag: 'OT',
    color: '#A855F7',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'cod',
    game: 'CALL OF DUTY',
    tag: 'OT',
    color: '#00A878',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'Slayer', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'AR', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'SMG', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'IGL', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'deadlock',
    game: 'DEADLOCK',
    tag: 'OT',
    color: '#E8191A',
    region: 'NA',
    roster: [
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Player', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
]

export const creators = [
  {
    id: 'creator1',
    handle: 'TBA',
    real: 'Coming Soon',
    platform: 'Twitch',
    followers: 'TBA',
    content: 'Coming Soon',
    country: '🇺🇸',
    specialty: 'TBA',
    bio: 'Creator details coming soon.',
    socials: { twitch: '', twitter: '', youtube: '' },
  },
]

export const partners = [
  {
    name: 'YOUR BRAND',
    category: 'Partner',
    tier: 'Founding',
    desc: 'Interested in partnering with Overtake? Reach out to us.',
  },
]

export const news = [
  {
    id: 1,
    title: 'OVERTAKE ACQUIRES NEW VALORANT TEAM',
    date: 'June 5, 2026',
    category: 'VALORANT',
    excerpt: 'Overtake expands its roster with the acquisition of a brand new Valorant team, ready to compete at the highest level.',
    link: 'https://x.com/OvertakeSector/status/2063004328445792649?s=20',
    image: 'https://pbs.twimg.com/media/GsDqX9NXoAAqKpQ?format=jpg',
  },
  {
    id: 2,
    title: 'OVERTAKE PICKS UP NEW DEADLOCK TEAM',
    date: 'June 5, 2026',
    category: 'DEADLOCK',
    excerpt: 'Overtake enters the Deadlock scene with a new roster ready to dominate the competition.',
    link: 'https://x.com/OvertakeSector/status/2062960141306085646?s=20',
    image: 'https://pbs.twimg.com/media/GsDFqWtWIAAUYmA?format=jpg',
  },
  {
    id: 3,
    title: 'OVERTAKE HAS A NEW ACADEMY TEAM',
    date: 'May 24, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake launches its new Academy team, developing the next generation of competitive talent.',
    link: 'https://x.com/OvertakeSector/status/2058581287791894651?s=20',
    image: 'https://pbs.twimg.com/media/Gr1gXqTXoAAqKpQ?format=jpg',
  },
  {
    id: 4,
    title: "OVERTAKE'S NEW FEMALE ROSTER",
    date: 'May 19, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake is proud to announce its new female Rainbow 6 roster, breaking barriers in competitive esports.',
    link: 'https://x.com/OvertakeSector/status/2056797030614172089?s=20',
    image: 'https://pbs.twimg.com/media/GrpXqWtXoAAUYmA?format=jpg',
  },
]
