export const teams = [
  {
    id: 'valo',
    game: 'VALORANT',
    tag: 'OT',
    color: '#FF4655',
    wins: 47,
    losses: 12,
    rank: '#3',
    region: 'NA',
    roster: [
      { name: 'PHANTOM', role: 'IGL', country: '🇺🇸', real: 'Marcus Chen', age: 22 },
      { name: 'VORTEX', role: 'Entry', country: '🇧🇷', real: 'Lucas Silva', age: 20 },
      { name: 'NEON', role: 'Sniper', country: '🇰🇷', real: 'Ji-ho Park', age: 21 },
      { name: 'CIPHER', role: 'Controller', country: '🇬🇧', real: 'Aiden Walsh', age: 23 },
      { name: 'SURGE', role: 'Flex', country: '🇸🇪', real: 'Erik Lindqvist', age: 19 },
    ],
  },
  {
    id: 'apex',
    game: 'APEX LEGENDS',
    tag: 'OT',
    color: '#CF4B00',
    wins: 31,
    losses: 8,
    rank: '#1',
    region: 'NA',
    roster: [
      { name: 'BLAZE', role: 'Fragger', country: '🇺🇸', real: 'Tyler Reed', age: 24 },
      { name: 'SPECTER', role: 'Support', country: '🇨🇦', real: 'Noah Tremblay', age: 22 },
      { name: 'RIOT', role: 'IGL', country: '🇦🇺', real: 'Caleb Stone', age: 25 },
    ],
  },
  {
    id: 'cod',
    game: 'CALL OF DUTY',
    tag: 'OT',
    color: '#00A878',
    wins: 28,
    losses: 19,
    rank: '#7',
    region: 'NA/EU',
    roster: [
      { name: 'WRAITH', role: 'Slayer', country: '🇺🇸', real: 'Jordan Hicks', age: 21 },
      { name: 'FRENZY', role: 'AR', country: '🇬🇧', real: 'Ryan O\'Brien', age: 20 },
      { name: 'ECHO', role: 'SMG', country: '🇫🇷', real: 'Antoine Moreau', age: 22 },
      { name: 'STEEL', role: 'IGL', country: '🇺🇸', real: 'Brandon Lee', age: 24 },
    ],
  },
  {
    id: 'rl',
    game: 'ROCKET LEAGUE',
    tag: 'OT',
    color: '#4B8BF5',
    wins: 54,
    losses: 22,
    rank: '#2',
    region: 'Global',
    roster: [
      { name: 'ORBIT', role: 'Midfielder', country: '🇩🇪', real: 'Felix Braun', age: 18 },
      { name: 'PULSE', role: 'Attacker', country: '🇳🇱', real: 'Daan Visser', age: 20 },
      { name: 'GRAVITY', role: 'Defender', country: '🇦🇺', real: 'Sam Porter', age: 19 },
    ],
  },
]

export const creators = [
  {
    id: 'nova',
    handle: 'NOVA',
    real: 'Alexis Park',
    platform: 'Twitch',
    followers: '2.4M',
    content: 'FPS Gameplay & Coaching',
    country: '🇰🇷',
    specialty: 'VALORANT',
    bio: 'Top-ranked VALORANT player turned full-time content creator. Known for insane mechanics and educational breakdowns.',
    socials: { twitch: 'nova_gg', twitter: 'nova_plays', youtube: 'novagg' },
  },
  {
    id: 'kai',
    handle: 'K4I',
    real: 'Kai Nakamura',
    platform: 'YouTube',
    followers: '1.8M',
    content: 'Battle Royale & Highlights',
    country: '🇯🇵',
    specialty: 'Apex Legends',
    bio: 'Legendary Apex player with the fastest hands in the East. His highlight reels break the internet weekly.',
    socials: { twitch: 'k4i_live', twitter: 'k4i_gg', youtube: 'k4i' },
  },
  {
    id: 'luna',
    handle: 'LUNA',
    real: 'Sofia Reyes',
    platform: 'TikTok',
    followers: '3.1M',
    content: 'Gaming Lifestyle & IRL',
    country: '🇲🇽',
    specialty: 'Multi-Title',
    bio: 'Where gaming meets culture. Luna\'s infectious energy and personality have made her one of esports\' most recognizable faces.',
    socials: { twitch: 'luna_live', twitter: 'lunaplays', youtube: 'lunagg' },
  },
  {
    id: 'ghost',
    handle: 'GH0ST',
    real: 'Damien Cross',
    platform: 'YouTube',
    followers: '990K',
    content: 'FPS Strategy & VOD Review',
    country: '🇺🇸',
    specialty: 'Call of Duty',
    bio: 'The tactician. GH0ST tears apart pro VODs and turns strategy into gold. A must-follow for serious competitors.',
    socials: { twitch: 'gh0st_live', twitter: 'gh0stgg', youtube: 'gh0st' },
  },
  {
    id: 'arc',
    handle: 'ARC',
    real: 'Priya Sharma',
    platform: 'Twitch',
    followers: '1.2M',
    content: 'Rocket League Pro Play',
    country: '🇮🇳',
    specialty: 'Rocket League',
    bio: 'First female Rocket League Grand Champion on the Overtake roster. ARC is redefining what\'s possible in competitive play.',
    socials: { twitch: 'arc_rl', twitter: 'arc_plays', youtube: 'arcrl' },
  },
  {
    id: 'raze',
    handle: 'RAZE',
    real: 'Dominic Turner',
    platform: 'Twitch',
    followers: '750K',
    content: 'Variety & Comedy Gaming',
    country: '🇦🇺',
    specialty: 'Multi-Title',
    bio: 'Arguably the funniest creator in esports. RAZE brings the chaos and the clips. Never a dull stream.',
    socials: { twitch: 'raze_live', twitter: 'razeplays', youtube: 'razegaming' },
  },
]

export const partners = [
  {
    name: 'NVIDIA',
    category: 'Hardware',
    tier: 'Founding',
    desc: 'Official GPU partner powering every Overtake workstation and gaming setup.',
  },
  {
    name: 'SteelSeries',
    category: 'Peripherals',
    tier: 'Founding',
    desc: 'Headsets, mice, and keyboards trusted by the pros. Official peripheral partner.',
  },
  {
    name: 'Red Bull',
    category: 'Energy',
    tier: 'Premier',
    desc: 'Fueling long sessions and tournament days. Gives you wings and frags.',
  },
  {
    name: 'HyperX',
    category: 'Memory & Gear',
    tier: 'Premier',
    desc: 'Official RAM and gear sponsor. HyperX performance in every match.',
  },
  {
    name: 'Secretlab',
    category: 'Furniture',
    tier: 'Official',
    desc: 'Where champions train. Secretlab chairs in every Overtake facility.',
  },
  {
    name: 'Discord',
    category: 'Communication',
    tier: 'Official',
    desc: 'Community and comms powered by Discord. Join our server today.',
  },
  {
    name: 'Alienware',
    category: 'Systems',
    tier: 'Official',
    desc: 'Tournament-grade gaming systems for the Overtake training facility.',
  },
  {
    name: 'GFuel',
    category: 'Energy',
    tier: 'Official',
    desc: 'The energy formula of esports. Exclusive Overtake flavor dropping soon.',
  },
]

export const news = [
  {
    id: 1,
    title: 'Overtake VALORANT Claims Top Seed at Challengers NA',
    date: 'May 28, 2025',
    category: 'VALORANT',
    excerpt: 'After a dominant group stage performance, OT VAL secures #1 seed heading into playoffs with a perfect 5-0 record.',
    image: null,
  },
  {
    id: 2,
    title: 'NOVA Crosses 2 Million Followers on Twitch',
    date: 'May 22, 2025',
    category: 'Content',
    excerpt: 'Overtake creator NOVA hits a massive milestone, cementing her place as one of the fastest-growing streamers in esports.',
    image: null,
  },
  {
    id: 3,
    title: 'BLAZE & SPECTER Re-Sign Multi-Year Deals with Overtake Apex',
    date: 'May 15, 2025',
    category: 'Apex Legends',
    excerpt: 'Two of the team\'s cornerstone players commit their futures to Overtake through 2027 in a landmark signing.',
    image: null,
  },
  {
    id: 4,
    title: 'Overtake Announces New Training Facility in Los Angeles',
    date: 'May 10, 2025',
    category: 'Organization',
    excerpt: 'A state-of-the-art 12,000 sq ft performance center opens this summer, housing all NA rosters under one roof.',
    image: null,
  },
  {
    id: 5,
    title: 'ORBIT Takes Home RLCS MVP Award at Spring Major',
    date: 'May 3, 2025',
    category: 'Rocket League',
    excerpt: 'At just 18 years old, ORBIT delivers a performance-of-the-tournament at RLCS Spring Major in Berlin.',
    image: null,
  },
  {
    id: 6,
    title: 'Founding Partnership with NVIDIA Extended Through 2027',
    date: 'April 28, 2025',
    category: 'Business',
    excerpt: 'Overtake and NVIDIA renew and expand their founding partnership in a deal that deepens technical collaboration.',
    image: null,
  },
]
